const products = [
    {
        id: 1,
        title: "SonicWave Pro",
        text: "Tauche ein in eine Klanglandschaft der Extraklasse mit den SonicWave Pro Kopfhörern. Genieße kristallklare Höhen, satte Mitten und kraftvolle Bässe, die jeden Ton in ein audiovisuelles Meisterwerk verwandeln.",
        imageNumber: 0,
        currentPrice: 99,
        oldPrice: 150,
    },
    {
        id: 2,
        title: "Harmony Beats",
        text: "Die Harmony Beats Kopfhörer bieten ein ausgewogenes Klangerlebnis, das Musik in ihrer reinsten Form präsentiert. Ein harmonisches Zusammenspiel von Klarheit und Tiefe, das audiophile Genießer begeistern wird.",
        imageNumber: 1,
        currentPrice: 149,
        oldPrice: 200,
    },
    {
        id: 3,
        title: "PureAudio Elite",
        text: "PureAudio Elite definiert audiophile Qualität neu. Erlebe makellose Klangreinheit und Präzision in einem stilvollen Design. Jeder Ton wird zu einem reinen Hörgenuss.",
        imageNumber: 2,
        currentPrice: 199,
        oldPrice: 250,
    },
    {
        id: 4,
        title: "AcousticFlow Fusion",
        text: "AcousticFlow Fusion kombiniert kraftvolle Akustik mit nahtlosem Design. Tauche ein in ein audiovisuelles Erlebnis, das Musik lebendig werden lässt. Erlebe die Fusion von Stil und Klang.",
        imageNumber: 3,
        currentPrice: 249,
        oldPrice: 300,
    },
    {
        id: 5,
        title: "SoundSculpt Xperience",
        text: "Mit SoundSculpt Xperience kannst du Musik neu erleben. Jeder Ton wird zu einer künstlerischen Skulptur, während du in die Welt der Klänge eintauchst. Ein Meisterwerk für deine Ohren.",
        imageNumber: 4,
        currentPrice: 49,
        oldPrice: 100,
    },
    {
        id: 6,
        title: "EchoHarbor Precision",
        text: "Die EchoHarbor Precision Kopfhörer bieten präzisen Sound in einem eleganten Gehäuse. Genieße jede Note mit unübertroffener Genauigkeit und entdecke die Feinheiten deiner Lieblingsmusik.",
        imageNumber: 5,
        currentPrice: 299,
        oldPrice: 350,
    },
    {
        id: 7,
        title: "Audiowave Fusion",
        text: "Die Audiowave Fusion Kopfhörer verschmelzen kraftvolle Bässe und klare Höhen zu einem harmonischen Klangabenteuer. Erlebe deine Musik in perfekter Symbiose.",
        imageNumber: 6,
        currentPrice: 99,
        oldPrice: 150,
    },
    {
        id: 8,
        title: "MelodyCraft Pro",
        text: "Mit MelodyCraft Pro kannst du jede Melodie in ihrer vollen Pracht genießen. Tauche ein in eine Welt von reichhaltigem Sound und klanglicher Raffinesse.",
        imageNumber: 7,
        currentPrice: 149,
        oldPrice: 200,
    },
    {
        id: 9,
        title: "SerenadeFlow Elite",
        text: "Die SerenadeFlow Elite Kopfhörer bieten ein elegantes Design und audiophile Klangleistung. Lass dich von einem harmonischen Fluss von Klängen umhüllen.",
        imageNumber: 8,
        currentPrice: 199,
        oldPrice: 250,
    },
    {
        id: 10,
        title: "HarborBeat Precision",
        text: "HarborBeat Precision liefert präzisen Sound im modernen Gewand. Jeder Ton wird mit höchster Genauigkeit wiedergegeben, für ein immersives Klangerlebnis.",
        imageNumber: 9,
        currentPrice: 249,
        oldPrice: 300,
    },
    {
        id: 11,
        title: "TuneSculpt Xperience",
        text: "Erlebe Musik neu mit den TuneSculpt Xperience Kopfhörern. Jeder Klang wird zu einer künstlerischen Skulptur, während du in die Tiefen deiner Lieblingsmusik eintauchst.",
        imageNumber: 10,
        currentPrice: 49,
        oldPrice: 100,
    },
    {
        id: 12,
        title: "SoundZenith Harmony",
        text: "SoundZenith Harmony vereint anspruchsvolles Design mit außergewöhnlicher Audioqualität. Tauche ein in einen harmonischen Klangraum, der jedes Musikgenre perfekt wiedergibt.",
        imageNumber: 11,
        currentPrice: 299,
        oldPrice: 350,
    },
]

export default products;